org: brittanisavery
app: siba
service: siba-api
useDotenv: true

custom:
  serverless-offline:
    httpPort: 4000
  serverless-offline-ses-v2:
    port: 8005

provider:
  name: aws
  runtime: nodejs16.x
  region: us-west-2
  environment:
    COMMISSIONER: ${env:COMMISSIONER_EMAIL}
    NO_REPLY: ${env:NO_REPLY_EMAIL}
    SITE_URL: ${env:SITE_URL}
    DB_NAME: ${env:DB_NAME}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_DB_NAME}

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ses:SendEmail"
          Resource: "*"

plugins:
  - serverless-offline
  - serverless-offline-ses-v2

functions:
  join:
    handler: handler.join
    events:
      - httpApi:
          path: /join
          method: POST

  upload:
    handler: handler.upload
    events:
      - httpApi:
          path: /member-uploads
          method: GET
