org: brittanisavery
app: siba
service: siba-api
useDotenv: true

custom:
  vars: ${file(vars.json)}
  defaultStage: dev
  serverless-offline:
    httpPort: 4000

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  environment:
    COMMISSIONER: ${self:custom.vars.${self:provider.stage}_commis_email}
    NO_REPLY: ${self:custom.vars.no_reply_email}
    SITE_URL: ${self:custom.vars.site_url}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ses:SendEmail"
          Resource: "*"

plugins:
  - serverless-offline

functions:
  join:
    handler: handler.join
    events:
      - http:
          path: siba/join
          method: post
          cors: true
